apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:        # <-- Correct position here (pod spec level)
      - name: ecr-secret
      containers:
        - name: mysql-container
          image: '097656145156.dkr.ecr.us-east-1.amazonaws.com/dbs_app:v1'
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
