# name: Terraform and Docker CI/CD Pipeline

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  infrastructure:
    name: Provision AWS Infrastructure
    runs-on: ubuntu-latest
    environment: staging
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    
    outputs:
      EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
    
      - name: Install AWS CLI and Boto3
        run: |
          pip install awscli boto3

      - name: Debug AWS Credentials
        run: |
          echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS Secret Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS Session Token: ${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: capture_terraform_outputs
        run: |
          echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

  docker_build_push:
    name: Build and Push Docker Images to ECR
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for ECR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Images
        run: |
          for service in web_app dbs_app; do
            docker build -t 097656145156.dkr.ecr.us-east-1.amazonaws.com/$service:latest -f Dockerfile_${service} .
            docker push 097656145156.dkr.ecr.us-east-1.amazonaws.com/$service:latest
          done
